# This file was generated by GoReleaser. DO NOT EDIT.
class Clone < Formula
  desc "Clone GitHub repositories conveniently."
  homepage "https://4d63.com/clone"
  version "2.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/leighmcculloch/clone/releases/download/v2.0.1/clone_2.0.1_darwin_amd64.tar.gz"
    sha256 "7914ab29c71065190d551985657138d513498c8ab6213608d3768257a259378f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/leighmcculloch/clone/releases/download/v2.0.1/clone_2.0.1_linux_amd64.tar.gz"
      sha256 "9f5ee35927cd9075169bc69b59745653e1542ed3bfd2ade71fd464b77628e984"
    end
  end

  def install
    bin.install "clone"
  end

  test do
    system "#{bin}/clone -help"
  end
end
